version: '3.9'
services:
  db:
    container_name: c_postgres_16
    image: postgres:16.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: javadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: kayascodelario
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
